apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: simple-app.corp.com.1.1.0
spec:
  refName: simple-app.corp.com
  version: 1.1.0
  releaseNotes: |
    TODO: Use a gh-action to compose a changelog
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        namespace:
          type: string
          default: simpleapp
          description: The namespace in which to deploy grafana.
        svc_port:
          type: integer
          default: 80
          description: Port number for the service.
        app_port:
          type: integer
          default: 80
          description: Target port for the application.
        hello_msg:
          type: string
          default: hello
          description: Name used in hello message from app when app is pinged.
        ingress:
          type: object
          additionalProperties: false
          properties:
            enabled:
              type: boolean
              default: false
            virtual_host_fqdn:
              type: string
              default: grafana.system.tanzu
            prefix:
              type: string
              default: /
            servicePort:
              type: integer
              default: 80
            tlsCertificate:
              type: object
              additionalProperties: false
              properties:
                tls.crt:
                  type: string
                  default: xxxx
                tls.key:
                  type: string
                  default: xxxx
                ca.crt:
                  type: string
                  default: xxxx
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: ghcr.io/javierfreire/carvel-repository-example-simple-app:1.1.0
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
