name: 'content-platform-simple-app'
on:
  pull_request:
env:
  CSP_API_URL: https://console.cloud.vmware.com
  CSP_API_TOKEN: ${{ secrets.CSP_API_TOKEN }}
  VIB_PUBLIC_URL: https://cp.bromelia.vmware.com
jobs:
  validation:
    name: K8s verify ${{ matrix.target-platform}}
    runs-on: ubuntu-latest
    environment: vmware-image-builder
    strategy:
      matrix:
        include:
          - target-platform: gke
            target-platform-id: 91d398a2-25c4-4cda-8732-75a3cfc179a1
          #- target-platform: aks
          #  target-platform-id: 7b13a7bb-011c-474f-ad71-8152fc321b9e
          #- target-platform: tkg
          #  target-platform-id: 7ddab896-2e4e-4d58-a501-f79897eba3a0
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: vmware-labs/vmware-image-builder-action@main
        with:
            pipeline: simple-app.json
        env:
          TARGET_PLATFORM: ${{ matrix.target-platform-id }}
